name: Release Charts

on:
  push:
    branches:
      - stable

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@vmain
        with:
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Index stable.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # Download chart-releaser
          curl -L https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_darwin_amd64.tar.gz --silent | tar -xz
          
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")

          args=(--owner "$owner" --repo "$repo")
          
          args+=(--index-path ".cr-index/stable.yaml" --push)
          args+=(--pages-index-path "stable.yaml" --push)

          echo 'Updating charts repo index stable.yaml...'
          cr index "${args[@]}"          
          #cr index --pages-index-path stable.yaml
